export const categories = [
    {
        id: 1,
        title: 'Novedades',
        slug: 'novedades-para-hombre',
        icon: '',
        priority: true,
    },
    {
        id: 2,
        title: 'Ropa',
        slug: 'ropa-para-hombre',
        icon: '',
        priority: false,
    },
    {
        id: 3,
        title: 'Accesorios',
        slug: 'accesorios-para-hombre',
        icon: '',
        priority: false,
    },
    {
        id: 4,
        title: 'Calzado',
        slug: 'calzado-para-hombre',
        icon: '',
        priority: false,
    },
    {
        id: 5,
        title: 'Ofertas',
        slug: 'ofertas-para-hombre',
        icon: '',
        priority: false,
    },
    {
        id: 6,
        title: 'Novedades',
        slug: 'novedades-para-mujer',
        icon: '',
        priority: false,
    },
    {
        id: 7,
        title: 'Ropa',
        slug: 'ropa-para-mujer',
        icon: '',
        priority: false,
    },
    {
        id: 8,
        title: 'Lencería',
        slug: 'lenceria',
        icon: '',
        priority: false,
    },
    {
        id: 9,
        title: 'Ropa de baño',
        slug: 'ropa-de-bano-para-mujer',
        icon: '',
        priority: true,
    },
    {
        id: 10,
        title: 'Accesorios',
        slug: 'accesorios-para-mujer',
        icon: '',
        priority: false,
    },
    {
        id: 11,
        title: 'Joyas y bisutería',
        slug: 'joyas-y-bisuteria-para-mujer',
        icon: '',
        priority: false,
    },
    {
        id: 12,
        title: 'Carteras',
        slug: 'carteras',
        icon: '',
        priority: false,
    },
    {
        id: 13,
        title: 'Calzado',
        slug: 'calzado-para-mujer',
        icon: '',
        priority: false,
    },
    {
        id: 14,
        title: 'Maquillaje',
        slug: 'maquillaje',
        icon: '',
        priority: false,
    },
    {
        id: 15,
        title: 'Ofertas',
        slug: 'ofertas-para-mujer',
        icon: '',
        priority: true,
    },
    {
        id: 16,
        title: 'Novedades',
        slug: 'novedades-belleza',
        icon: '',
        priority: true,
    },
    {
        id: 17,
        title: 'Cuidado/Aseo personal',
        slug: 'cuidado-y-aseo-personal',
        icon: '',
        priority: false,
    },
    {
        id: 18,
        title: 'Ofertas',
        slug: 'ofertas-belleza',
        icon: '',
        priority: false,
    },
    {
        id: 19,
        title: 'Juegos de mesa',
        slug: 'juegos-de-mesa',
        icon: '',
        priority: false,
    },
    {
        id: 20,
        title: 'Juegos para niños',
        slug: 'jugueteria-ninos',
        icon: '',
        priority: true,
    },
]